- name: Provision User Monitoring
  include_tasks: provision_monitoring.yml
  when:
  - enable_user_workload_monitoring
  - provision_demo | bool

- name: Configure User Monitoring
  include_tasks: configure_monitoring.yml
  when:
  - enable_user_workload_monitoring
  - provision_demo | bool

- name: Delete Monitoring
  include_tasks: delete_monitoring.yml
  when: delete_demo | bool
