- hosts: localhost
  name: Install RHI Demo
  vars:
    demo_delete: false
    demo_project: rhi-demo
    cicd_project: rhi-demo-cicd
    threescale_project: rhi-demo-threescale
    threescale_account_user: rhidemouser
    threescale_account_org: rhi-demo-org
    threescale_account_password: rhidemopassword
    registry_url: quay.io/gcamposo
    ingestor_git: https://gitlab.com/rhi-demo/salesforce-webhook-ingestor.git
    asana_adapter_git: https://gitlab.com/rhi-demo/asana-adapter.git
    insecure_skip_tls_verify: true
    enable_logging: false
    enable_user_workload_monitoring: false
    enable_pipelines: true
  tasks:

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443')   }}"

    - name: login as super user with token on OpenShift 4
      command: "oc login --token={{ token }}  --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
      when:
       - token is defined
       - server is defined
      ignore_errors: no

    - name: Create demo_project project
      k8s:
        state: present
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ demo_project }}"
            annotations:
              openshift.io/description: ""
              openshift.io/display-name: "RHI Demo Project"


    - name: Enable User Monitoring
      include_tasks: tasks/enable_user_project_monitoring.yml
      when: enable_user_workload_monitoring

    - name: Enable Log Stack
      include_tasks: tasks/provision_log_stack.yml
      when: enable_logging

    - name: Enable GitOps
      include_tasks: tasks/provision_gitops.yml

    - name: Configure RHI Demo GitOps
      include_tasks: tasks/configure_gitops.yml

    - name: Enable Pipelines
      include_tasks: tasks/provision_pipelines.yml
      when: enable_pipelines

    - name: Configure RHI Demo Pipelines
      include_tasks: tasks/configure_pipelines.yml
      when: enable_pipelines

    - name: Enable 3scale
      include_tasks: tasks/provision_3scale.yml

    - name: Configure RHI Demo 3scale
      include_tasks: tasks/configure_3scale.yml

    # - name: Delete 3scale
    #   include_tasks: tasks/delete_3scale.yml
