- hosts: localhost
  name: Install RHI Demo
  vars:
    demo_delete: false
    demo_project: rhi-demo
    insecure_skip_tls_verify: true
  tasks:

    - name: login as super user with token on OpenShift 4
      command: "oc login --token={{ token }}  --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
      when:
       - token is defined
       - server is defined
      ignore_errors: no

    - name: Create demo_project project
      k8s:
        state: present
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ demo_project }}"
            annotations:
              openshift.io/description: ""
              openshift.io/display-name: "RHI Demo Project"

    - name: Provision Camel K Operator
      include_tasks: tasks/provision_camelk.yml

    - name: Enable User Monitoring
      include_tasks: tasks/enable_user_project_monitoring.yml

    - name: Enable Log Stack
      include_tasks: tasks/provision_log_stack.yml

    - name: Enable Pipelines
      include_tasks: tasks/provision_pipelines.yml      
