- name: Delete Istio Control Plane instance
  k8s:
    state: absent
    resource_definition: "{{ lookup('template', 'ossm_control_plane.yml.j2') }}"

- name: Delete Jaeger Subscription
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    definition:
      metadata:
        name: jaeger-product
        namespace: openshift-operators

- name: Delete Kiali Subscription
  k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    definition:
      metadata:
        name: kiali-operator
        namespace: openshift-operators

- name: Delete Service Mesh Subscription
  k8s:
    state: present
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    definition:
      metadata:
        name: redhat-service-mesh-operator
        namespace: openshift-operators
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: servicemeshoperator
        source: redhat-operators
        sourceNamespace: openshift-marketplace


- name: Delete istio-system Namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: istio-system
    state: absent
