- name: Delete 3scale
  include_tasks: tasks/delete_3scale.yml

- name: Delete Service Mesh
  include_tasks: tasks/delete_ossm.yml

- name: Delete Monitoring
  include_tasks: tasks/delete_monitoring.yml

- name: Delete Pipeline
  include_tasks: tasks/delete_pipeline.yml

- name: Delete GitOps
  include_tasks: tasks/delete_gitops.yml

- name: Delete {{ demo_project }} Namespace
  k8s:
    state: absent
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ demo_project }}"
        annotations:
          openshift.io/description: "Namespace used to deploy RHI Demo applications"
          openshift.io/display-name: "RHI Demo Project"
