---

- name: Check OpenShift GitOps Subscription
  k8s:
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: openshift-gitops-operator
        namespace: openshift-operators
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: openshift-gitops-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Waiting for GitOps Subscription to complete
  shell: set -o pipefail && oc get csv -n openshift-operators | grep openshift-gitops-operator
  register: install_status
  until: "'Succeeded' in install_status.stdout"
  retries: 20
  delay: 15
  args:
    executable: /bin/bash

- name: Evaluate GitOps Permissions
  k8s:
    state: present
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    definition:
      metadata:
        name: edit-0
        namespace: '{{ demo_project }}'
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: ServiceAccount
        name: openshift-gitops-argocd-application-controller
        namespace: openshift-gitops

- name: Evaluate salesforce-secret exists
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'secret_salesforce.yml.j2') }}"

- name: Evaluate salesforce-webhook-ingestor GitOps Application
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'argo_ingestor.yml.j2') }}"

- name: Evaluate asana-secret exists
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'secret_asana.yml.j2') }}"

- name: Evaluate asana-adapter GitOps Application
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'argo_asana_adapter.yml.j2') }}"
