---

- name: Check ElasticSearch Namespace
  k8s:
    state: present
    kind: Namespace
    api_version: v1
    definition:
      metadata:
        name: openshift-operators-redhat
        annotations:
          openshift.io/node-selector: ""
        labels:
          openshift.io/cluster-monitoring: "true"

- name: Check openshift-operators-redhat OperatorGroup
  k8s:
    state: present
    kind: OperatorGroup
    api_version: operators.coreos.com/v1
    definition:
      metadata:
        name: openshift-operators-redhat
        namespace: openshift-operators-redhat
      spec: {}

- name: Check ElasticSearch Subscription
  k8s:
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: "elasticsearch-operator"
        namespace: "openshift-operators-redhat"
      spec:
        channel: stable
        installPlanApproval: Automatic
        name: elasticsearch-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Check Logging Operator Namespace
  k8s:
    state: present
    kind: Namespace
    api_version: v1
    definition:
      metadata:
        name: openshift-logging
        annotations:
          openshift.io/node-selector: ""
        labels:
          openshift.io/cluster-monitoring: "true"

- name: Check openshift-logging OperatorGroup
  k8s:
    state: present
    kind: OperatorGroup
    api_version: operators.coreos.com/v1
    definition:
      metadata:
        name: cluster-logging
        namespace: openshift-logging
      spec:
        targetNamespaces:
        - openshift-logging

- name: Check logging Subscription
  k8s:
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
        metadata:
          name: cluster-logging
          namespace: openshift-logging
        spec:
          channel: "stable"
          name: cluster-logging
          source: redhat-operators
          sourceNamespace: openshift-marketplace

- name: Wait for the deployments to be created
  pause:
      minutes: 2

- name: Check if Logging Operator is ready
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: cluster-logging-operator
    namespace: openshift-logging
  register: r_logging_deploy
  retries: 50
  delay: 10
  until: r_logging_deploy.resources[0].status.readyReplicas == 1

- name: Check if ElasticSearch Operator is ready
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: elasticsearch-operator
    namespace: openshift-operators-redhat
  register: r_es_deploy
  retries: 50
  delay: 10
  until: r_es_deploy.resources[0].status.readyReplicas == 1

# - name: Result
#   debug:
#     msg: "{{r_codeready_crd}}"


- name: Check Logging Instance
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', './files/logging-instance.yml' ) | from_yaml }}"
