- name: Evaluate {{ cicd_project }} project
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    kind: Project
    api_version: project.openshift.io/v1
    definition:
      metadata:
        name: "{{ cicd_project }}"
        annotations:
          openshift.io/description: ""
          openshift.io/display-name: "RHI Demo CICD Project"

- name: Evalute Pipeline ServiceAccount Permissions
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    definition:
      metadata:
        name: pipeline-edit
        namespace: '{{ demo_project }}'
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: edit
      subjects:
      - kind: ServiceAccount
        name: pipeline
        namespace: '{{ cicd_project }}'

- name: Evaluate quay-secret
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    resource_definition: "{{ lookup('template', 'secret_quay.yml.j2') }}"

- name: Evaluate ArgoCD Secret
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    kind: Secret
    api_version: v1
    definition:
      metadata:
        name: argocd-env-secret
        namespace: '{{ cicd_project }}'
      stringData:
        ARGOCD_USERNAME: admin
        ARGOCD_PASSWORD: '{{ argo_password }}'
      type: Opaque

- name: Evaluate ArgoCD ConfigMap
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    kind: ConfigMap
    api_version: v1
    definition:
      metadata:
        name: argocd-env-configmap
        namespace: '{{ cicd_project }}'
      data:
        ARGOCD_SERVER: openshift-gitops-server.openshift-gitops

- name: Evaluate PVCs
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    resource_definition: "{{ lookup('template', 'tekton_pvcs.yml.j2') }}"

- name: Evaluate buildah Task
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    resource_definition: "{{ lookup('template', 'tekton_task_buildah.yml.j2') }}"

- name: Evaluate maven-version Task
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    resource_definition: "{{ lookup('template', 'tekton_task_maven_version.yml.j2') }}"

- name: Evaluate argo-sync Task
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    resource_definition: "{{ lookup('template', 'tekton_task_argo.yml.j2') }}"

- name: Evaluate salesforce-webhook-ingestor Pipeline
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    resource_definition: "{{ lookup('template', 'tekton_pipeline_ingestor.yml.j2') }}"

- name: Evaluate asana-adapter Pipeline
  k8s:
    api_key: '{{ token }}'
    host: '{{ server }}'
    validate_certs: no
    state: present
    resource_definition: "{{ lookup('template', 'tekton_pipeline_asana_adapter.yml.j2') }}"
