- name: Check Pipelines Subscription
  k8s:
    state: present
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    definition:
      metadata:
        name: openshift-pipelines-operator
        namespace: openshift-operators
      spec:
        installPlanApproval: Automatic
        channel:  stable
        name: openshift-pipelines-operator-rh
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Wait for Pipeline Subscription to complete
  shell: set -o pipefail && oc get csv -n openshift-operators | grep redhat-openshift-pipelines
  register: install_status
  until: "'Succeeded' in install_status.stdout"
  retries: 20
  delay: 15
  args:
    executable: /bin/bash
