- hosts: localhost
  name: Install RHI Demo
  vars:
    demo_delete: false
    demo_project: rhi-demo
    cicd_project: rhi-demo-cicd
    grafana_project: rhi-demo-grafana
    grafana_user: root
    grafana_password: secret
    threescale_project: rhi-demo-threescale
    insecure_skip_tls_verify: true
    enable_logging: true
    enable_user_workload_monitoring: true
    enable_pipelines: true
    delete_demo: false
  tasks:

    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443')   }}"

    - name: login as super user with token on OpenShift 4
      command: "oc login --token={{ token }}  --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
      when:
       - token is defined
       - server is defined
      ignore_errors: no

    - name: Evaluate {{ demo_project }} Namespace
      when: not delete_demo
      k8s:
        state: present
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ demo_project }}"
            annotations:
              openshift.io/description: "Namespace used to deploy RHI Demo applications"
              openshift.io/display-name: "RHI Demo Project"

    - name: Evaluate Operator Group
      when: not delete_demo
      k8s:
        state: present
        api_version: operators.coreos.com/v1
        kind: OperatorGroup
        definition:
          metadata:
            name: '{{ demo_project }}-operatorgroup'
            namespace: '{{ demo_project}}'
          spec:
            targetNamespaces:
            - '{{ demo_project }}'

    - name: Include Logging role
      include_role:
        name: logging

    - name: Include Monitoring role
      include_role:
        name: monitoring

    - name: Include Threescale role
      include_role:
        name: threescale

    - name: Include Service Mesh role
      include_role:
        name: ossm

    - name: Include ArgoCD role
      include_role:
        name: argocd

    - name: Include Tekton role
      when: enable_pipelines | bool
      include_role:
        name: tekton

    - name: Delete {{ demo_project }} Namespace
      when: delete_demo | bool
      k8s:
        state: absent
        kind: Project
        api_version: project.openshift.io/v1
        definition:
          metadata:
            name: "{{ demo_project }}"
            annotations:
              openshift.io/description: "Namespace used to deploy RHI Demo applications"
              openshift.io/display-name: "RHI Demo Project"

    - name: Print Information
      when: not delete_demo
      include_role:
        name: results
